name: User Test

on: 
  push: 
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building container
        run: |
          docker-compose up -d --build
      - name: Running Tests
        run: |
          docker-compose exec -T api test